/*
 * Copyright 2004-2016 EPAM Systems
 * This file is part of Java Market Data Handler for CME Market Data (MDP 3.0).
 * Java Market Data Handler for CME Market Data (MDP 3.0) is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Java Market Data Handler for CME Market Data (MDP 3.0) is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Java Market Data Handler for CME Market Data (MDP 3.0).
 * If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/schema">http://java.sun.com/xml/schema</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 01:02:39 PM MSK 
//


package com.epam.cme.mdp3.sbe.schema.vo;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="types" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType" maxOccurs="unbounded"/>
 *                   &lt;element name="composite" type="{http://www.fixprotocol.org/ns/simple/1.0}compositeDataType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="enum" type="{http://www.fixprotocol.org/ns/simple/1.0}enumType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="set" type="{http://www.fixprotocol.org/ns/simple/1.0}setType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message" type="{http://www.fixprotocol.org/ns/simple/1.0}messageType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="semanticVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="byteOrder" default="littleEndian">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="bigEndian"/>
 *             &lt;enumeration value="littleEndian"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "types",
        "message"
})
@XmlRootElement(name = "messageSchema")
public class MessageSchema {

    @XmlElement(required = true)
    protected List<MessageSchema.Types> types;
    @XmlElement(required = true)
    protected List<MessageType> message;
    @XmlAttribute(name = "package")
    protected String _package;
    @XmlAttribute(name = "semanticVersion")
    protected String semanticVersion;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "byteOrder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String byteOrder;

    /**
     * Gets the value of the types property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the types property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypes().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageSchema.Types }
     */
    public List<MessageSchema.Types> getTypes() {
        if (types == null) {
            types = new ArrayList<>();
        }
        return this.types;
    }

    /**
     * Gets the value of the message property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageType }
     */
    public List<MessageType> getMessage() {
        if (message == null) {
            message = new ArrayList<>();
        }
        return this.message;
    }

    /**
     * Gets the value of the package property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the semanticVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSemanticVersion() {
        return semanticVersion;
    }

    /**
     * Sets the value of the semanticVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSemanticVersion(String value) {
        this.semanticVersion = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the byteOrder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getByteOrder() {
        if (byteOrder == null) {
            return "littleEndian";
        } else {
            return byteOrder;
        }
    }

    /**
     * Sets the value of the byteOrder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setByteOrder(String value) {
        this.byteOrder = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://www.fixprotocol.org/ns/simple/1.0}encodedDataType" maxOccurs="unbounded"/>
     *         &lt;element name="composite" type="{http://www.fixprotocol.org/ns/simple/1.0}compositeDataType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="enum" type="{http://www.fixprotocol.org/ns/simple/1.0}enumType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="set" type="{http://www.fixprotocol.org/ns/simple/1.0}setType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "type",
            "composite",
            "_enum",
            "set"
    })
    public static class Types {

        @XmlElement(required = true)
        protected List<EncodedDataType> type;
        protected List<CompositeDataType> composite;
        @XmlElement(name = "enum")
        protected List<EnumType> _enum;
        protected List<SetType> set;

        /**
         * Gets the value of the type property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the type property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getType().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EncodedDataType }
         */
        public List<EncodedDataType> getType() {
            if (type == null) {
                type = new ArrayList<>();
            }
            return this.type;
        }

        /**
         * Gets the value of the composite property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the composite property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComposite().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompositeDataType }
         */
        public List<CompositeDataType> getComposite() {
            if (composite == null) {
                composite = new ArrayList<>();
            }
            return this.composite;
        }

        /**
         * Gets the value of the enum property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the enum property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEnum().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EnumType }
         */
        public List<EnumType> getEnum() {
            if (_enum == null) {
                _enum = new ArrayList<>();
            }
            return this._enum;
        }

        /**
         * Gets the value of the set property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the set property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSet().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SetType }
         */
        public List<SetType> getSet() {
            if (set == null) {
                set = new ArrayList<>();
            }
            return this.set;
        }

    }

}
