/*
 * Copyright 2004-2016 EPAM Systems
 * This file is part of Java Market Data Handler for CME Market Data (MDP 3.0).
 * Java Market Data Handler for CME Market Data (MDP 3.0) is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Java Market Data Handler for CME Market Data (MDP 3.0) is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Java Market Data Handler for CME Market Data (MDP 3.0).
 * If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/schema">http://java.sun.com/xml/schema</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 01:02:39 PM MSK 
//


package com.epam.cme.mdp3.sbe.schema.vo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * com.epam.mdp.full.coders.mdp the com.epam.mdp.sbe.schema.schema package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of sccom.epam.mdp.full.coders.mdp classes for package: com.epam.mdp.sbe.schema.schema
     */
    ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageSchema }
     */
    public MessageSchema createMessageSchema() {
        return new MessageSchema();
    }

    /**
     * Create an instance of {@link MessageSchema.Types }
     */
    public MessageSchema.Types createMessageSchemaTypes() {
        return new MessageSchema.Types();
    }

    /**
     * Create an instance of {@link MessageType }
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link GroupType }
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link EncodedDataType }
     */
    public EncodedDataType createEncodedDataType() {
        return new EncodedDataType();
    }

    /**
     * Create an instance of {@link CompositeDataType }
     */
    public CompositeDataType createCompositeDataType() {
        return new CompositeDataType();
    }

    /**
     * Create an instance of {@link Choice }
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link FieldType }
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link SetType }
     */
    public SetType createSetType() {
        return new SetType();
    }

    /**
     * Create an instance of {@link EnumType }
     */
    public EnumType createEnumType() {
        return new EnumType();
    }

    /**
     * Create an instance of {@link ValidValue }
     */
    public ValidValue createValidValue() {
        return new ValidValue();
    }

}
