/*
 * Copyright 2004-2016 EPAM Systems
 * This file is part of Java Market Data Handler for CME Market Data (MDP 3.0).
 * Java Market Data Handler for CME Market Data (MDP 3.0) is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Java Market Data Handler for CME Market Data (MDP 3.0) is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Java Market Data Handler for CME Market Data (MDP 3.0).
 * If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/schema">http://java.sun.com/xml/schema</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 01:02:39 PM MSK 
//


package com.epam.cme.mdp3.sbe.schema.vo;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * Simple data type of a field
 * <p>
 * <p>Java class for encodedDataType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="encodedDataType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>token">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="presence" default="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="required"/>
 *             &lt;enumeration value="optional"/>
 *             &lt;enumeration value="constant"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nullValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="1" />
 *       &lt;attribute name="variableLength" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="semanticType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primitiveType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="char"/>
 *             &lt;enumeration value="int8"/>
 *             &lt;enumeration value="int16"/>
 *             &lt;enumeration value="int32"/>
 *             &lt;enumeration value="int64"/>
 *             &lt;enumeration value="uint8"/>
 *             &lt;enumeration value="uint16"/>
 *             &lt;enumeration value="uint32"/>
 *             &lt;enumeration value="uint64"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "encodedDataType", propOrder = {
        "value"
})
public class EncodedDataType {

    @XmlValue
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String value;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "presence")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String presence;
    @XmlAttribute(name = "nullValue")
    protected String nullValue;
    @XmlAttribute(name = "minValue")
    protected String minValue;
    @XmlAttribute(name = "maxValue")
    protected String maxValue;
    @XmlAttribute(name = "length")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger length;
    @XmlAttribute(name = "variableLength")
    protected Boolean variableLength;
    @XmlAttribute(name = "semanticType")
    protected String semanticType;
    @XmlAttribute(name = "primitiveType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String primitiveType;
    @XmlAttribute(name = "offset")
    protected int offset;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the presence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPresence() {
        if (presence == null) {
            return "required";
        } else {
            return presence;
        }
    }

    /**
     * Sets the value of the presence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPresence(String value) {
        this.presence = value;
    }

    /**
     * Gets the value of the nullValue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNullValue() {
        return nullValue;
    }

    /**
     * Sets the value of the nullValue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNullValue(String value) {
        this.nullValue = value;
    }

    /**
     * Gets the value of the minValue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMinValue(String value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxValue(String value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the length property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getLength() {
        if (length == null) {
            return new BigInteger("1");
        } else {
            return length;
        }
    }

    /**
     * Sets the value of the length property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

    /**
     * Gets the value of the variableLength property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isVariableLength() {
        if (variableLength == null) {
            return false;
        } else {
            return variableLength;
        }
    }

    /**
     * Sets the value of the variableLength property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setVariableLength(Boolean value) {
        this.variableLength = value;
    }

    /**
     * Gets the value of the semanticType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSemanticType() {
        return semanticType;
    }

    /**
     * Sets the value of the semanticType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSemanticType(String value) {
        this.semanticType = value;
    }

    /**
     * Gets the value of the primitiveType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrimitiveType() {
        return primitiveType;
    }

    /**
     * Sets the value of the primitiveType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrimitiveType(String value) {
        this.primitiveType = value;
    }

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }
}
