/*
 * Copyright 2004-2016 EPAM Systems
 * This file is part of Java Market Data Handler for CME Market Data (MDP 3.0).
 * Java Market Data Handler for CME Market Data (MDP 3.0) is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Java Market Data Handler for CME Market Data (MDP 3.0) is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Java Market Data Handler for CME Market Data (MDP 3.0).
 * If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/schema">http://java.sun.com/xml/schema</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 01:02:39 PM MSK 
//


package com.epam.cme.mdp3.sbe.schema.vo;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for messageType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="messageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" type="{http://www.fixprotocol.org/ns/simple/1.0}fieldType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="group" type="{http://www.fixprotocol.org/ns/simple/1.0}groupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="data" type="{http://www.fixprotocol.org/ns/simple/1.0}fieldType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="blockLength" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="fixMsgType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="semanticType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "messageType", propOrder = {
        "field",
        "group",
        "data"
})
public class MessageType {

    protected List<FieldType> field;
    protected List<GroupType> group;
    protected List<FieldType> data;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int id;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "blockLength")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger blockLength;
    @XmlAttribute(name = "fixMsgType")
    protected String fixMsgType;
    @XmlAttribute(name = "semanticType")
    protected String semanticType;

    /**
     * Gets the value of the field property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldType }
     */
    public List<FieldType> getField() {
        if (field == null) {
            field = new ArrayList<>();
        }
        return this.field;
    }

    /**
     * Gets the value of the group property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupType }
     */
    public List<GroupType> getGroup() {
        if (group == null) {
            group = new ArrayList<>();
        }
        return this.group;
    }

    /**
     * Gets the value of the data property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldType }
     */
    public List<FieldType> getData() {
        if (data == null) {
            data = new ArrayList<>();
        }
        return this.data;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the blockLength property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getBlockLength() {
        return blockLength;
    }

    /**
     * Sets the value of the blockLength property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setBlockLength(BigInteger value) {
        this.blockLength = value;
    }

    /**
     * Gets the value of the fixMsgType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFixMsgType() {
        return fixMsgType;
    }

    /**
     * Sets the value of the fixMsgType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFixMsgType(String value) {
        this.fixMsgType = value;
    }

    /**
     * Gets the value of the semanticType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSemanticType() {
        return semanticType;
    }

    /**
     * Sets the value of the semanticType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSemanticType(String value) {
        this.semanticType = value;
    }

}
